### ISSUE TITLE
Warning on the frontend console on first click after reload of a diagram

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1029]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 2022.01.0
* [x] **I have specified my environment** : Linux

### Screenshots

https://user-images.githubusercontent.com/10608/151934366-2e3d57f9-4092-42a9-8cd2-14af994dcc41.mp4

### Steps to reproduce

1. Open an existing (non-empty) diagram
2. Open the browser devtools and make sure the console is visible
3. Refresh the browser page, and immediatly after, click on a node in the diagram

The contextual palette opens as expected (and everything seems to work fine), but we get a React warning in the console:

```
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ContextualPalette`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at ContextualPalette (http://localhost:3000/static/js/vendors~main.chunk.js:24278:35)
    at div
    at div
    at div
    at DropArea (http://localhost:3000/static/js/vendors~main.chunk.js:19919:32)
    at div
    at div
    at DiagramWebSocketContainer (http://localhost:3000/static/js/vendors~main.chunk.js:25857:33)
    at div
    at div
    at div
    at Panels (http://localhost:3000/static/js/vendors~main.chunk.js:12800:26)
    at div
    at div
    at div
    at Panels (http://localhost:3000/static/js/vendors~main.chunk.js:12800:26)
    at Workbench (http://localhost:3000/static/js/vendors~main.chunk.js:40353:33)
    at div
    at EditProjectView (http://localhost:3000/static/js/main.chunk.js:2919:85)
    at ErrorBoundary (http://localhost:3000/static/js/vendors~main.chunk.js:26912:172)
    at Route (http://localhost:3000/static/js/vendors~main.chunk.js:151999:29)
    at Switch (http://localhost:3000/static/js/vendors~main.chunk.js:152201:29)
    at Main
    at div
    at ThemeProvider (http://localhost:3000/static/js/vendors~main.chunk.js:79252:24)
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:151634:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:151254:35)
    at ApolloProvider (http://localhost:3000/static/js/vendors~main.chunk.js:7198:19)
```

This only happens on the first click/selection after the page refresh.

**Comment by pcdavid** [comment]
Can't reproduce on current master (`ContextualPalette` visible in the stack refers to the old code base).
