### ISSUE TITLE
Fix the way the cross references are cleaned

### ISSUE THREAD

**Issue by lfasani** [eclipse-sirius/sirius-web#1400]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

### Screenshots

...

### Steps to reproduce

* import the attached Flow model [Flow.zip](https://github.com/eclipse-sirius/sirius-components/files/9774679/Flow.zip)
* remove the model

```
Caused by: org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=2, size=0
    at org.eclipse.emf.common.util.BasicEList.basicGet(BasicEList.java:363) ~[org.eclipse.emf.common-2.21.0.jar:na]
    at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:515) ~[org.eclipse.emf.ecore-2.23.0.jar:na]
    at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.next(EContentsEList.java:595) ~[org.eclipse.emf.ecore-2.23.0.jar:na]
    at org.eclipse.emf.ecore.util.EcoreUtil$ProperContentIterator.hasNext(EcoreUtil.java:1368) ~[org.eclipse.emf.ecore-2.23.0.jar:na]
    at org.eclipse.emf.common.util.AbstractTreeIterator.next(AbstractTreeIterator.java:154) ~[org.eclipse.emf.common-2.21.0.jar:na]
    at org.eclipse.sirius.components.emf.services.EditingContextCrossReferenceAdapter.handleRemoveResource(EditingContextCrossReferenceAdapter.java:80) ~[classes/:na]
    ```

### Expected behavior

There should not be any exception and the cross references should be properly cleaned

### Actual behavior

...

**Comment by lfasani** [comment]
I am not sure but a lead is that the issue probably happen when the model contains instances of objects that have feature `container=false` (corresponds to containment reference which have its opposite)
