### ISSUE TITLE
Objects may be created using multiple strategies which can create incompatible objects in a single model

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1591]
When we are creating the root objects of a resource, we are loading on the fly the EPackages  from scratch without considering existing EPackages loaded in the package registry of the editing domain.

<img width="2048" alt="01 - New root object UI" src="https://user-images.githubusercontent.com/422587/213419866-7224f312-b122-42e0-b4f9-1011ee198d13.png">
<img width="2048" alt="02 - Invalid EPackage" src="https://user-images.githubusercontent.com/422587/213419871-f6af5135-0c6c-466d-992c-de7076abf34b.png">

When we are creating objects using a dedicated tool from the view DSL with some model operations, they are created using the EPackages available in the package registry of the editing domain.

Let's consider a click on `New Operational Entity` which comes with a dedicated node tool using the view DSL.

<img width="2048" alt="03 - New object from view with createInstance model operation" src="https://user-images.githubusercontent.com/422587/213420115-8ddc9666-490b-405c-90e9-7b5a2426aa5b.png">
<img width="2048" alt="04 - Create instance model operation behavior" src="https://user-images.githubusercontent.com/422587/213420128-7d6543c9-250d-4916-8a6f-db4dc3efabbc.png">

As a result, it is quite easy to create a model in which the root object and objects created using the view DSL do not share the same EPackage. For some reason, this does not seems to create any issue in my case.

<img width="2048" alt="05 - Incompatible EPackages" src="https://user-images.githubusercontent.com/422587/213420355-d8d4d822-21ca-45fe-bf0e-a3a5373ecf42.png">

The problem becomes obvious since, when we are creating objects using the view DSL thanks to a canonical tool, the EPackage used is the EPackage of `self` and thus the source of the metamodel to use may change depending on the target of the tool.

Let's consider a click on `New Operational Actor` which rely on the canonical behavior.

<img width="2048" alt="06 - Creating new child using the canonical behavior" src="https://user-images.githubusercontent.com/422587/213420687-4efbd697-469b-487b-a91a-4220c4f92e9b.png">
<img width="2048" alt="07 - The canonical behavior uses the EPackage of the container" src="https://user-images.githubusercontent.com/422587/213420707-3cc2617d-2313-419d-ab84-c25e6c944ee3.png">

Now we will end up with two subgraphs of objects in our domain using the same concepts from two versions of our EPackage.

<img width="2048" alt="08 - Using the canonical behavior again" src="https://user-images.githubusercontent.com/422587/213421139-55d34584-6388-4f51-a42f-0c09c08c1189.png">
<img width="2048" alt="09 - Trying to create an edge between the two objects" src="https://user-images.githubusercontent.com/422587/213421144-c0341607-b957-4d24-b1fe-53d06bcb25e6.png">

**Comment by pcdavid** [comment]
Example stack trace (to make it easier to search for the issue):
```
java.util.concurrent.ExecutionException: java.lang.ClassCastException: The value of type 'org.eclipse.emf.ecore.impl.EClassImpl@31245735 (name: Component) (instanceClassName: null) (abstract: false, interface: false)' must be of type 'org.eclipse.emf.ecore.impl.EClassImpl@4ccbab80 (name: Component) (instanceClassName: null) (abstract: false, interface: false)'
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.handle(EditingContextEventProcessor.java:217) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessorRegistry.lambda$1(EditingContextEventProcessorRegistry.java:76) ~[classes/:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessorRegistry.dispatchEvent(EditingContextEventProcessorRegistry.java:76) ~[classes/:na]
	at org.eclipse.sirius.components.starter.services.EditingContextDispatcher.dispatchMutation(EditingContextDispatcher.java:54) ~[classes/:na]
	at org.eclipse.sirius.components.diagrams.graphql.datafetchers.mutation.MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.lambda$0(MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.java:57) ~[classes/:na]
	at org.eclipse.sirius.components.starter.services.ExceptionWrapper.wrapMono(ExceptionWrapper.java:61) ~[classes/:na]
	at org.eclipse.sirius.components.diagrams.graphql.datafetchers.mutation.MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.get(MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.java:57) ~[classes/:na]
	at org.eclipse.sirius.components.diagrams.graphql.datafetchers.mutation.MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.get(MutationInvokeSingleClickOnTwoDiagramElementsToolDataFetcher.java:1) ~[classes/:na]
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:87) ~[graphql-java-18.3.jar:na]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:279) ~[graphql-java-18.3.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:210) ~[graphql-java-18.3.jar:na]
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:182) ~[graphql-java-18.3.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:43) ~[graphql-java-18.3.jar:na]
	at graphql.execution.Async.eachSequentiallyImpl(Async.java:80) ~[graphql-java-18.3.jar:na]
	at graphql.execution.Async.eachSequentially(Async.java:69) ~[graphql-java-18.3.jar:na]
	at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:38) ~[graphql-java-18.3.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:159) ~[graphql-java-18.3.jar:na]
	at graphql.execution.Execution.execute(Execution.java:105) ~[graphql-java-18.3.jar:na]
```
