### ISSUE TITLE
Rename a representation/document with a name length > 50 characters is not properly handled

### ISSUE THREAD

**Issue by AxelRICHARD** [eclipse-sirius/sirius-web#1775]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

### Stack trace

Server stack trace after the rename:

```
2023-03-01 09:37:39.625 ERROR 98777 --- [14-f65b9545938c] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: new row for relation "representation" violates check constraint "representation_label_length"
  Détail : Failing row contains (df0bc3ba-3685-4a04-8ddf-2467f05262ff, 46e24162-b280-4843-af14-f65b9545938c, 4518b809-169c-473a-ac7a-b0a7ed36cb5a, Averyveryveryverylongnamewithoutspacesazertyuiopaz, siriusComponents://representation?type=Diagram, 29228857-eb70-346d-ba1f-b6844b21a977, {"id":"df0bc3ba-3685-4a04-8ddf-2467f05262ff","kind":"siriusCompo...).
2023-03-01 09:37:39.627  INFO 98777 --- [14-f65b9545938c] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2023-03-01 09:37:39.653  WARN 98777 --- [14-f65b9545938c] o.e.s.c.c.e.EditingContextEventProcessor : could not execute statement; SQL [n/a]; constraint [representation_label_length]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [representation_label_length]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.23.jar:5.3.23]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566) ~[spring-orm-
	at ...
	at org.eclipse.sirius.web.services.representations.RepresentationService.save(RepresentationService.java:123) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.handlers.RenameDiagramEventHandler.handle(RenameDiagramEventHandler.java:91) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessor.handle(DiagramEventProcessor.java:119) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.handleRepresentationInput(EditingContextEventProcessor.java:325) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.doHandle(EditingContextEventProcessor.java:245) ~[classes/:na]
	at ... org.eclipse.sirius.components.collaborative.trees.handlers.RenameTreeItemEventHandler.handle(RenameTreeItemEventHandler.java:110) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.trees.TreeEventProcessor.handle(TreeEventProcessor.java:118) ~[classes/:na]
	....
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:109) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:46) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3571) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3438) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3852) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:202) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[na:na]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:344) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1407) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:489) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3303) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2438) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:449) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101) ~[hibernate-core-5.6.12.Final.jar:5.6.12.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562) ~[spring-orm-5.3.23.jar:5.3.23]
	... 36 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: new row for relation "representation" violates check constraint "representation_label_length"
  Détail : Failing row contains (df0bc3ba-3685-4a04-8ddf-2467f05262ff, 46e24162-b280-4843-af14-f65b9545938c, 4518b809-169c-473a-ac7a-b0a7ed36cb5a, Averyveryveryverylongnamewithoutspacesazertyuiopaz, siriusComponents://representation?type=Diagram, 29228857-eb70-346d-ba1f-b6844b21a977, {"id":"df0bc3ba-3685-4a04-8ddf-2467f05262ff","kind":"siriusCompo...).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675) ~[postgresql-42.3.7.jar:42.3.7]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365) ~[postgresql-42.3.7.jar:42.3.7]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355) ~[postgresql-42.3.7.jar:42.3.7]
	... 58 common frames omitted
```

### Steps to reproduce

1. Use the Robot Flow model
2. Select the System item in the Explorer View
3. Create a new representation on the system element with name > 50 characters

### Expected behavior

The new name is taken into account or is not taken into account but an error message appears in the snackbar.
It is possible to rename any other tree item or any field in the details view after that.

### Actual behavior

The new name is not taken into account.
It is impossible to rename any other tree item or any field in the details view after that.

**Comment by AxelRICHARD** [comment]
As agreed with. @sbegaudeau, the decision is to increase representation/document/project label length from 50 to 1024 characters maximum in Sirius-Web SQL schema file

**Comment by AxelRICHARD** [comment]
Increase representation/document/project label length from 50 to 1024 characters maximum in sirius-web SQL schema.

Handle long label in UI by adding ellipsis after 100 characters in projects page, edit project navbar, and explorer.
