### ISSUE TITLE
ExplorerNavigationService#getAncestors fails on non-UUID selectionEntryId

### ISSUE THREAD

**Issue by gdaniel** [eclipse-sirius/sirius-web#2436]
The following line in `ExplorerNavigationService` produces an `IllegalArgumentException` when the `selectioEntryId` String is not an UUID.  
```java
var optionalRepresentation = this.representationService.getRepresentation(UUID.fromString(selectionEntryId));
```

The exception is thrown by `UUID.fromString(String)`. 

Note that `ObjectService#getId(Object)` can return a non-UUID String (e.g. a URI fragment), and the `getAncestors` method can handle non-UUID IDs in the following line:
```java
var optionalSemanticObject = this.objectService.getObject(editingContext, selectionEntryId);
```

It seems that the method shouldn't look for a `RepresentationDescriptor` if `selectionEntryId` is not a valid UUID.

* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 2023.8.3
* [x] **I have specified my environment** : windows (didn't try on another platform)

### Screenshots

Relevant stack trace
```
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: UML.metamodel.uml#ReduceAction
	at java.base/java.util.UUID.fromString1(UUID.java:280) ~[na:na]
	at java.base/java.util.UUID.fromString(UUID.java:258) ~[na:na]
	at org.eclipse.sirius.web.services.explorer.ExplorerNavigationService.getAncestors(ExplorerNavigationService.java:51) ~[sirius-web-services-2023.8.3.jar:2023.8.3]
	at org.eclipse.sirius.web.services.explorer.ExplorerTreePathProvider.handle(ExplorerTreePathProvider.java:54) ~[sirius-web-services-2023.8.3.jar:2023.8.3]
	at org.eclipse.sirius.components.collaborative.trees.handlers.TreePathEventHandler.handle(TreePathEventHandler.java:71) ~[sirius-components-collaborative-trees-2023.8.3.jar:2023.8.3]
	at org.eclipse.sirius.components.collaborative.trees.TreeEventProcessor.handle(TreeEventProcessor.java:118) ~[sirius-components-collaborative-trees-2023.8.3.jar:2023.8.3]
```

### Steps to reproduce

Call `ExplorerNavigationService#getAncestors` with a non-UUID `selectionEntryId`. 

### Expected behavior

`ExplorerNavigationService#getAncestors` returns the list of ancestors or an empty list when the `selectionEntryId` is a non-UUID String.

### Actual behavior

`ExplorerNavigationService#getAncestors` throws an `IllegalArgumentException`.

**Comment by sbegaudeau** [comment]
Just a couple of comments:

- `IObjectService#getId` lets specifiers provide any kind of String. `ObjectService#getId(Object)` can indeed return something other than an UUID but in Sirius Web right know, I don't think there's a single valid use case which should return something other than an UUID. It should only happen in applications derived from Sirius Web.
- `ExplorerNavigationService#getAncestors` does not support anything other than UUID, that's not what the input can be (any string is a valid input here) but in Sirius Web, as of today, we should only have UUIDs here too.

While Sirius Components allows any String, Sirius Web uses UUID all the time. In order to match more closely what can be expressed with Sirius Components, we should support `String` instead of `UUID` as the identifier of the representation (even if we keep storing a UUID in said string). We should thus change `RepresentationDescriptor#id`, the repository, the database schema etc.
