### ISSUE TITLE
The ViewRepresentationDescriptionSearchService cannot work beyond basic use cases

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#2888]
We had the `DynamicRepresentationDescriptionService` which was responsible for loading the various view models to be converted by the editing context. This service has been improved multiple time to handle more complex use cases over time. As an example, it loads all view models to resolve proxies or it supports the static view model containing the default color palette. On the other hand, the `ViewRepresentationDescriptionSearchService` can end up loading one view document straight from the database without any support for those features. It ends up creating EMF resources with proxies which cannot be resolved.

As a result, several features ends up being broken such as the support for drag and drop since we have proxies:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.resource.Resource.getURI()" because the return value of "org.eclipse.emf.ecore.EObject.eResource()" is null
	at org.eclipse.sirius.components.view.emf.diagram.DiagramIdProvider.getSourceIdFromElementDescription(DiagramIdProvider.java:58) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DiagramIdProvider.getId(DiagramIdProvider.java:48) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.lambda$computeDropNodeCompatibility$2(DropNodeCompatibiliyProvider.java:85) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.visitUnseenNodeDescriptions(DropNodeCompatibiliyProvider.java:109) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.visitUnseenNodeDescriptions(DropNodeCompatibiliyProvider.java:112) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.forEachNodeDescription(DropNodeCompatibiliyProvider.java:103) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.computeDropNodeCompatibility(DropNodeCompatibiliyProvider.java:84) ~[classes/:na]
	at org.eclipse.sirius.components.view.emf.diagram.DropNodeCompatibiliyProvider.getDropNodeCompatibility(DropNodeCompatibiliyProvider.java:67) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.handlers.GetDropNodeCompatibilityEventHandler.lambda$handle$1(GetDropNodeCompatibilityEventHandler.java:93) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
	at org.eclipse.sirius.components.collaborative.diagrams.handlers.GetDropNodeCompatibilityEventHandler.handle(GetDropNodeCompatibilityEventHandler.java:93) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessor.handle(DiagramEventProcessor.java:168) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.handleRepresentationInput(EditingContextEventProcessor.java:345) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.doHandle(EditingContextEventProcessor.java:273) ~[classes/:na]
	at org.eclipse.sirius.components.collaborative.editingcontext.EditingContextEventProcessor.lambda$handle$2(EditingContextEventProcessor.java:239) ~[classes/:na]
	at org.eclipse.sirius.components.web.concurrent.DelegatingRequestContextRunnable.run(DelegatingRequestContextRunnable.java:40) ~[classes/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	... 1 common frames omitted
```

**Comment by sbegaudeau** [comment]
Closing this issue since a fix has been merged during 2024.3.0
