### ISSUE TITLE
Exception in ModelBrowsersDescriptionProvider

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#2950]
Not sure what's the scenario to trigger this, but seen in the logs:

```
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "java.util.Map.get(Object)" is null
    at org.eclipse.sirius.components.collaborative.widget.reference.browser.ModelBrowsersDescriptionProvider.resolveReferenceEClass(ModelBrowsersDescriptionProvider.java:174) ~[sirius-components-collaborative-widget-reference-2023.12.9.jar!/:2023.12.9]
    at org.eclipse.sirius.components.collaborative.widget.reference.browser.ModelBrowsersDescriptionProvider.lambda$addRepresentationDescriptions$2(ModelBrowsersDescriptionProvider.java:93) ~[sirius-components-collaborative-widget-reference-2023.12.9.jar!/:2023.12.9]
    at org.eclipse.sirius.components.trees.renderer.TreeRenderer.renderTreeItem(TreeRenderer.java:67) ~[sirius-components-trees-2023.12.9.jar!/:2023.12.9]
    at org.eclipse.sirius.components.trees.renderer.TreeRenderer.render(TreeRenderer.java:51) ~[sirius-components-trees-2023.12.9.jar!/:2023.12.9]
```

**Comment by frouene** [comment]
I am reproducing by using a non-existent reference for a reference widget
